
import type { Game, MonetizationPlan, User } from './types';
import { Language, Theme } from './types';
import ChessGame from './features/games/chess/ChessGame';
import CheckersGame from './features/games/checkers/CheckersGame';
import TicTacToeGame from './features/games/tic-tac-toe/TicTacToeGame';
import SudokuGame from './features/games/sudoku/SudokuGame';
import WordMasterGame from './features/games/wordmaster/WordMasterGame';
import PacmanGame from './features/games/pacman/PacmanGame';
import TetrisGame from './features/games/tetris/TetrisGame';
import MonopolyGame from './features/games/monopoly/MonopolyGame';
import LudoGame from './features/games/ludo/LudoGame';
import HangmanGame from './features/games/hangman/HangmanGame';
import Game2048 from './features/games/2048/Game2048';
import UnoGame from './features/games/uno/UnoGame';
import SnakeGame from './features/games/snake/SnakeGame';
import BattleshipGame from './features/games/battleship/BattleshipGame';
import ScrabbleGame from './features/games/scrabble/ScrabbleGame';
import ClueGame from './features/games/clue/ClueGame';
import TicketToRideGame from './features/games/ticket-to-ride/TicketToRideGame';
import PandemicGame from './features/games/pandemic/PandemicGame';
import Civ2Game from './features/games/civ2/Civ2Game';
import KSPGame from './features/games/ksp/KSPGame';
import RacingGame from './features/games/racing/RacingGame';

const DIFF_OPTIONS = [
  { value: 'junior', labelKey: 'junior' },
  { value: 'beginner', labelKey: 'beginner' },
  { value: 'intermediate', labelKey: 'intermediate' },
  { value: 'advanced', labelKey: 'advanced' }
];

export const GAMES: Game[] = [
  {
    id: 'chess',
    nameKey: 'chess',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: ChessGame,
    descriptionKey: 'chess_desc',
    rulesKey: 'chess_rules',
    historyKey: 'chess_history',
    funFactsKey: ['chess_fact1', 'chess_fact2', 'chess_fact3'],
    options: [{ id: 'difficulty', labelKey: 'difficulty_level', type: 'select', values: DIFF_OPTIONS.slice(1), defaultValue: 'intermediate' }],
  },
  {
    id: 'checkers',
    nameKey: 'checkers',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: CheckersGame,
    descriptionKey: 'checkers_desc',
    rulesKey: 'checkers_rules',
    historyKey: 'checkers_history',
    funFactsKey: ['checkers_fact1', 'checkers_fact2'],
    options: [{ id: 'difficulty', labelKey: 'difficulty_level', type: 'select', values: DIFF_OPTIONS.slice(1), defaultValue: 'intermediate' }],
  },
  {
    id: 'tic-tac-toe',
    nameKey: 'tictactoe',
    categoryKey: 'puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: TicTacToeGame,
    descriptionKey: 'tictactoe_desc',
    rulesKey: 'tictactoe_rules',
    historyKey: 'tictactoe_history',
    funFactsKey: ['tictactoe_fact1', 'tictactoe_fact2'],
  },
  {
    id: 'sudoku',
    nameKey: 'sudoku',
    categoryKey: 'puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: SudokuGame,
    descriptionKey: 'sudoku_desc',
    rulesKey: 'sudoku_rules',
    historyKey: 'sudoku_history',
    funFactsKey: ['sudoku_fact1', 'sudoku_fact2'],
    options: [{ id: 'difficulty', labelKey: 'difficulty_level', type: 'select', values: DIFF_OPTIONS, defaultValue: 'junior' }],
  },
  {
    id: 'wordmaster',
    nameKey: 'wordmaster',
    categoryKey: 'word',
    status: 'playable',
    enabled: true,
    visible: true,
    component: WordMasterGame,
    descriptionKey: 'wordmaster_desc',
    rulesKey: 'wordmaster_rules',
    historyKey: 'wordmaster_history',
    funFactsKey: ['wordmaster_fact1', 'wordmaster_fact2'],
  },
  {
    id: 'ludo',
    nameKey: 'ludo',
    categoryKey: 'board',
    status: 'playable',
    enabled: true,
    visible: true,
    component: LudoGame,
    descriptionKey: 'ludo_desc',
    rulesKey: 'ludo_rules',
    historyKey: 'ludo_history',
    funFactsKey: ['ludo_fact1'],
  },
  {
    id: 'snake',
    nameKey: 'snake',
    categoryKey: 'arcade',
    status: 'playable',
    enabled: true,
    visible: true,
    component: SnakeGame,
    descriptionKey: 'snake_desc',
    rulesKey: 'snake_rules',
    historyKey: 'snake_history',
    funFactsKey: ['snake_fact1'],
  },
  {
    id: 'pacman',
    nameKey: 'pacman',
    categoryKey: 'arcade',
    status: 'playable',
    enabled: true,
    visible: true,
    component: PacmanGame,
    descriptionKey: 'pacman_desc',
    rulesKey: 'pacman_rules',
    historyKey: 'pacman_history',
    funFactsKey: ['pacman_fact1'],
  },
  {
    id: 'tetris',
    nameKey: 'tetris',
    categoryKey: 'puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: TetrisGame,
    descriptionKey: 'tetris_desc',
    rulesKey: 'tetris_rules',
    historyKey: 'tetris_history',
    funFactsKey: ['tetris_fact1'],
  },
  {
    id: 'monopoly',
    nameKey: 'monopoly',
    categoryKey: 'board',
    status: 'playable',
    enabled: true,
    visible: true,
    component: MonopolyGame,
    descriptionKey: 'monopoly_desc',
    rulesKey: 'monopoly_rules',
    historyKey: 'monopoly_history',
    funFactsKey: ['monopoly_fact1'],
  },
  {
    id: 'hangman',
    nameKey: 'hangman',
    categoryKey: 'word',
    status: 'playable',
    enabled: true,
    visible: true,
    component: HangmanGame,
    descriptionKey: 'hangman_desc',
    rulesKey: 'hangman_rules',
    historyKey: 'hangman_history',
    funFactsKey: ['hangman_fact1'],
  },
  {
    id: '2048',
    nameKey: 'game2048',
    categoryKey: 'puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: Game2048,
    descriptionKey: '2048_desc',
    rulesKey: '2048_rules',
    historyKey: '2048_history',
    funFactsKey: ['2048_fact1'],
  },
  {
    id: 'uno',
    nameKey: 'uno',
    categoryKey: 'card',
    status: 'playable',
    enabled: true,
    visible: true,
    component: UnoGame,
    descriptionKey: 'uno_desc',
    rulesKey: 'uno_rules',
    historyKey: 'uno_history',
    funFactsKey: ['uno_fact1'],
  },
  {
    id: 'battleship',
    nameKey: 'battleship',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: BattleshipGame,
    descriptionKey: 'battleship_desc',
    rulesKey: 'battleship_rules',
    historyKey: 'battleship_history',
    funFactsKey: ['battleship_fact1'],
  },
  {
    id: 'scrabble',
    nameKey: 'scrabble',
    categoryKey: 'word',
    status: 'playable',
    enabled: true,
    visible: true,
    component: ScrabbleGame,
    descriptionKey: 'scrabble_desc',
    rulesKey: 'scrabble_rules',
    historyKey: 'scrabble_history',
    funFactsKey: ['scrabble_fact1'],
  },
  {
    id: 'clue',
    nameKey: 'clue',
    categoryKey: 'board',
    status: 'playable',
    enabled: true,
    visible: true,
    component: ClueGame,
    descriptionKey: 'clue_desc',
    rulesKey: 'clue_rules',
    historyKey: 'clue_history',
    funFactsKey: ['clue_fact1'],
  },
  {
    id: 'ticket_to_ride',
    nameKey: 'ticket_to_ride',
    categoryKey: 'board',
    status: 'playable',
    enabled: true,
    visible: true,
    component: TicketToRideGame,
    descriptionKey: 'ttr_desc',
    rulesKey: 'ttr_rules',
    historyKey: 'ttr_history',
    funFactsKey: ['ttr_fact1'],
  },
  {
    id: 'pandemic',
    nameKey: 'pandemic',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: PandemicGame,
    descriptionKey: 'pandemic_desc',
    rulesKey: 'pandemic_rules',
    historyKey: 'pandemic_history',
    funFactsKey: ['pandemic_fact1'],
  },
  {
    id: 'civ2',
    nameKey: 'civ2',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: Civ2Game,
    descriptionKey: 'civ2_desc',
    rulesKey: 'civ2_rules',
    historyKey: 'civ2_history',
    funFactsKey: ['civ2_fact1'],
  },
  {
    id: 'ksp',
    nameKey: 'ksp',
    categoryKey: 'arcade',
    status: 'playable',
    enabled: true,
    visible: true,
    component: KSPGame,
    descriptionKey: 'ksp_desc',
    rulesKey: 'ksp_rules',
    historyKey: 'ksp_history',
    funFactsKey: ['ksp_fact1'],
  },
  {
    id: 'racing',
    nameKey: 'racing',
    categoryKey: 'arcade',
    status: 'playable',
    enabled: true,
    visible: true,
    component: RacingGame,
    descriptionKey: 'racing_desc',
    rulesKey: 'racing_rules',
    historyKey: 'racing_history',
    funFactsKey: ['racing_fact1'],
  },
];

const en = {
  'alile_play': 'Alile Play',
  'game_library': 'Library',
  'pricing': 'Pricing',
  'about': 'About',
  'feedback': 'Feedback',
  'feedback_title': 'Evaluation & Monitoring',
  'play_now': 'Play Now',
  'junior': 'Junior (K-6)',
  'beginner': 'Beginner',
  'intermediate': 'Intermediate',
  'advanced': 'Advanced',
  'difficulty_level': 'Difficulty Level',
  'rules': 'Rules',
  'history': 'History',
  'fun_facts': 'Fun Facts',
  'score': 'Score',
  'new_game': 'New Game',
  'reset_board': 'Reset Board',
  'game_over': 'Game Over!',
  'play_again': 'Play Again',
  'game_lobby': 'Game Lobby',
  'game_options': 'Options',
  'start_game': 'Start Game',
  'wordmaster_win': 'Magnificent! You found the word.',
  'wordmaster_lose': 'Out of tries! The word was:',
  'chess': 'Chess',
  'chess_desc': 'The ultimate game of strategy and logic.',
  'chess_rules': 'Control the center. Checkmate the enemy King. Use standard FIDE piece movements.',
  'chess_history': 'Born from Chaturanga in 6th-century India, Chess evolved through Persia to Europe.',
  'chess_fact1': 'There are more possible chess games than atoms in the observable universe.',
  'chess_fact2': 'A computer first defeated a world champion in 1997 (Deep Blue).',
  'checkers': 'Checkers',
  'checkers_desc': 'Classic diagonal jumping board game.',
  'checkers_rules': 'Move diagonally. Jump over opponent pieces to capture them. Reach the last row to King your piece.',
  'checkers_history': 'Played in ancient Mesopotamia as early as 3000 BC.',
  'checkers_fact1': 'Checkers was solved in 2007; perfect play by both sides leads to a draw.',
  'tictactoe': 'Tic Tac Toe',
  'tictactoe_desc': 'Three in a row wins the game.',
  'tictactoe_rules': 'Align 3 Xs or Os horizontally, vertically, or diagonally on a 3x3 grid.',
  'tictactoe_history': 'Ancient Egyptians played grid-based alignment games over 3,000 years ago.',
  'tictactoe_fact1': 'There are 255,168 possible game variants.',
  'sudoku': 'Sudoku',
  'sudoku_desc': 'Logic-based number placement puzzle.',
  'sudoku_rules': 'Fill the grid so every row, column, and subgrid contains digits 1-9 (or 1-4 for Junior) once.',
  'sudoku_history': 'Popularized in Japan during the 1980s by the publisher Nikoli.',
  'sudoku_fact1': 'Junior Sudoku (4x4) is educationally certified for K-6 foundational logic training.',
  'ludo': 'Ludo',
  'ludo_desc': 'Race your tokens home.',
  'ludo_rules': 'Roll a 6 to enter the track. Move clockwise. Landing on an opponent sends them back to the base.',
  'ludo_history': 'Based on the ancient Indian game "Pachisi", played by Mughal Emperors.',
  'ludo_fact1': 'Ludo means "I play" in Latin.',
  'snake': 'Snake',
  'snake_desc': 'Eat, grow, and avoid the walls.',
  'snake_rules': 'Control the snake to eat the food. Each meal makes you grow longer. Collision ends the game.',
  'snake_history': 'Global fame came in 1998 when pre-installed on Nokia mobile phones.',
  'snake_fact1': 'The longest possible game ends when the snake fills every single tile on the grid.',
  'wordmaster': 'Word Master',
  'wordmaster_desc': 'Guess the secret 5-letter word.',
  'wordmaster_rules': 'Green: Correct spot. Yellow: Wrong spot. Gray: Not in word.',
  'wordmaster_history': 'Inspired by the 1970s game Mastermind and modern viral word puzzles.',
  'wordmaster_fact1': 'The best starting word is statistically calculated to be "CRANE" or "ADIEU".',
  'game2048': '2048',
  '2048_desc': 'Join tiles to reach 2048.',
  '2048_rules': 'Swipe to merge identical tiles. They combine into their sum. Reach 2048 to win.',
  '2048_history': 'Developed in a single weekend by 19-year-old Gabriele Cirulli in 2014.',
  '2048_fact1': 'The highest possible tile value is theoretically 131,072.',
  'red': 'Red', 'blue': 'Blue', 'green': 'Green', 'yellow': 'Yellow',
};

const fr = {
  'alile_play': 'Alile Play',
  'game_library': 'Bibliothèque',
  'pricing': 'Tarifs',
  'about': 'À Propos',
  'feedback': 'Avis',
  'feedback_title': 'Évaluation et Surveillance',
  'play_now': 'Jouer',
  'junior': 'Junior (K-6)',
  'beginner': 'Débutant',
  'intermediate': 'Intermédiaire',
  'advanced': 'Avancé',
  'difficulty_level': 'Niveau de Difficulté',
  'rules': 'Règles',
  'history': 'Histoire',
  'fun_facts': 'Infos',
  'score': 'Score',
  'new_game': 'Nouveau Jeu',
  'reset_board': 'Réinitialiser',
  'game_over': 'Terminé !',
  'play_again': 'Rejouer',
  'game_lobby': 'Salon du Jeu',
  'game_options': 'Options',
  'start_game': 'Lancer le Jeu',
  'wordmaster_win': 'Magnifique ! Vous avez trouvé le mot.',
  'chess': 'Échecs',
  'chess_desc': 'Le jeu ultime de stratégie et de logique.',
  'chess_rules': 'Échec et mat au roi ennemi. Contrôlez le centre. Utilisez les mouvements FIDE.',
  'chess_history': 'Originaire de l\'Inde (Chaturanga) au VIe siècle, perfectionné en Europe.',
  'checkers': 'Dames',
  'checkers_desc': 'Stratégie de sauts diagonaux classique.',
  'checkers_rules': 'Déplacez-vous en diagonale. Sautez par-dessus les pions ennemis pour les capturer.',
  'tictactoe': 'Morpion',
  'tictactoe_desc': 'Alignez trois symboles pour gagner.',
  'sudoku': 'Sudoku',
  'sudoku_desc': 'Casse-tête logique de chiffres.',
  'sudoku_rules': 'Chaque ligne, colonne et sous-grille doit contenir tous les chiffres sans répétition.',
  'sudoku_fact1': 'Le niveau Junior (4x4) est conçu pour l\'éducation des enfants K-6.',
  'ludo': 'Ludo',
  'ludo_desc': 'Course de jetons vers la maison.',
  'ludo_rules': 'Faites un 6 pour sortir de la base. Avancez dans le sens des aiguilles d\'une montre.',
  'snake': 'Serpent',
  'snake_desc': 'Mangez pour grandir, évitez les murs.',
  'snake_rules': 'Utilisez les flèches pour manger. Ne touchez pas votre queue.',
  'game2048': '2048',
  '2048_desc': 'Fusionnez les tuiles pour atteindre 2048.',
  'red': 'Rouge', 'blue': 'Bleu', 'green': 'Vert', 'yellow': 'Jaune',
};

const es = {
  'alile_play': 'Alile Play',
  'game_library': 'Biblioteca',
  'pricing': 'Precios',
  'about': 'Acerca de',
  'feedback': 'Opiniones',
  'feedback_title': 'Evaluación y Monitoreo',
  'play_now': 'Jugar Ahora',
  'junior': 'Junior (K-6)',
  'beginner': 'Principiante',
  'intermediate': 'Intermedio',
  'advanced': 'Avanzado',
  'difficulty_level': 'Nivel de Dificultad',
  'rules': 'Reglas',
  'history': 'Historia',
  'fun_facts': 'Curiosidades',
  'score': 'Puntuación',
  'new_game': 'Nuevo Juego',
  'reset_board': 'Reiniciar Tablero',
  'game_over': '¡Juego Terminado!',
  'play_again': 'Jugar de Nuevo',
  'game_lobby': 'Salón del Juego',
  'start_game': 'Empezar',
  'wordmaster_win': '¡Magnífico! Encontraste la palabra.',
  'chess': 'Ajedrez',
  'chess_desc': 'El juego definitivo de estrategia y lógica.',
  'chess_rules': 'Haz jaque mate al rey enemigo. Controla el centro del tablero.',
  'tictactoe': 'Tres en Raya',
  'tictactoe_desc': 'Alinea tres símbolos para ganar.',
  'sudoku': 'Sudoku',
  'sudoku_desc': 'Rompecabezas lógico de números.',
  'sudoku_fact1': 'El nivel Junior utiliza una cuadrícula de 4x4 para el entrenamiento lógico.',
  'ludo': 'Ludo',
  'ludo_desc': 'Carrera de fichas a casa.',
  'ludo_rules': 'Saca un 6 para entrar. Mueve las fichas en sentido horario.',
  'snake': 'Serpiente',
  'game2048': '2048',
  'red': 'Rojo', 'blue': 'Azul', 'green': 'Verde', 'yellow': 'Amarillo',
};

const zh = {
  'alile_play': 'Alile Play',
  'game_library': '游戏库',
  'pricing': '定价',
  'about': '关于',
  'feedback': '反馈',
  'feedback_title': '评估与监控',
  'play_now': '现在玩',
  'junior': '初级 (K-6)',
  'beginner': '入门',
  'intermediate': '中级',
  'advanced': '高级',
  'difficulty_level': '难度级别',
  'rules': '规则',
  'history': '历史',
  'fun_facts': '趣味知识',
  'score': '分数',
  'new_game': '新游戏',
  'reset_board': '重置面板',
  'game_over': '游戏结束！',
  'play_again': '再玩一次',
  'game_lobby': '游戏大厅',
  'start_game': '开始游戏',
  'wordmaster_win': '太棒了！你找到了单词。',
  'chess': '国际象棋',
  'chess_desc': '终极战略与逻辑游戏。',
  'chess_rules': '将死对方国王。控制中心区域。',
  'tictactoe': '井字棋',
  'tictactoe_desc': '三连胜即可获胜。',
  'sudoku': '数独',
  'sudoku_desc': '基于逻辑的数字拼图。',
  'sudoku_fact1': '初级水平使用4x4网格进行逻辑训练。',
  'ludo': '飞行棋',
  'ludo_desc': '将你的代币赛跑回家。',
  'snake': '贪吃蛇',
  'game2048': '2048',
  'red': '红色', 'blue': '蓝色', 'green': '绿色', 'yellow': '黄色',
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: en,
  fr: fr,
  es: es,
  de: { ...en },
  zh: zh,
  pt: { ...en },
};

export const DEFAULT_USER: User = {
  name: 'Guest Player',
  role: 'public',
  preferences: { theme: Theme.DARK, language: Language.EN, skillLevels: {} },
  subscription: { planId: 'free', gamesPlayedThisMonth: 0, gamePlays: {} },
};

export const PLANS: MonetizationPlan[] = [
  { id: 'free', nameKey: 'plan_free', price: 0, featuresKey: ['Access to 10 Basic Games', 'Limited Plays'], isFeatured: false },
  { id: 'pro', nameKey: 'plan_pro', price: 9, featuresKey: ['Access to All 21 Games', 'Unlimited Plays', 'AI Strategy Tips'], isFeatured: true },
];
