
import type { Game, MonetizationPlan, User } from './types';
import { Language, Theme } from './types';
import ChessGame from './features/games/chess/ChessGame';
import CheckersGame from './features/games/checkers/CheckersGame';
import TicTacToeGame from './features/games/tic-tac-toe/TicTacToeGame';
import SudokuGame from './features/games/sudoku/SudokuGame';
import WordMasterGame from './features/games/wordmaster/WordMasterGame';
import PacmanGame from './features/games/pacman/PacmanGame';
import TetrisGame from './features/games/tetris/TetrisGame';
import MonopolyGame from './features/games/monopoly/MonopolyGame';
import LudoGame from './features/games/ludo/LudoGame';
import HangmanGame from './features/games/hangman/HangmanGame';
import Game2048 from './features/games/2048/Game2048';
import UnoGame from './features/games/uno/UnoGame';
import SnakeGame from './features/games/snake/SnakeGame';
import BattleshipGame from './features/games/battleship/BattleshipGame';
import ScrabbleGame from './features/games/scrabble/ScrabbleGame';
import ClueGame from './features/games/clue/ClueGame';
import TicketToRideGame from './features/games/ticket-to-ride/TicketToRideGame';
import PandemicGame from './features/games/pandemic/PandemicGame';
import Civ2Game from './features/games/civ2/Civ2Game';
import KSPGame from './features/games/ksp/KSPGame';
import RacingGame from './features/games/racing/RacingGame';
import Connect4Game from './features/games/connect4/Connect4Game';

const DIFF_OPTIONS = [
  { value: 'junior', labelKey: 'junior' },
  { value: 'beginner', labelKey: 'beginner' },
  { value: 'intermediate', labelKey: 'intermediate' },
  { value: 'advanced', labelKey: 'advanced' }
];

const PLAY_MODE_OPTIONS = [
  { value: 'pvp', labelKey: 'Local PVP' },
  { value: 'pva', labelKey: 'Player vs AI' }
];

export const GAMES: Game[] = [
  {
    id: 'chess',
    nameKey: 'chess',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: ChessGame,
    descriptionKey: 'chess_desc',
    rulesKey: 'chess_rules',
    historyKey: 'chess_history',
    funFactsKey: ['chess_fact1', 'chess_fact2', 'chess_fact3'],
    options: [{ id: 'difficulty', labelKey: 'difficulty_level', type: 'select', values: DIFF_OPTIONS.slice(1), defaultValue: 'intermediate' }],
  },
  {
    id: 'checkers',
    nameKey: 'checkers',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: CheckersGame,
    descriptionKey: 'checkers_desc',
    rulesKey: 'checkers_rules',
    historyKey: 'checkers_history',
    funFactsKey: ['checkers_fact1', 'checkers_fact2'],
    options: [
      { id: 'play_mode', labelKey: 'Game Mode', type: 'select', values: PLAY_MODE_OPTIONS, defaultValue: 'pva' },
      { id: 'difficulty', labelKey: 'AI Difficulty', type: 'select', values: DIFF_OPTIONS.slice(1), defaultValue: 'intermediate' }
    ],
  },
  {
    id: 'tic-tac-toe',
    nameKey: 'tictactoe',
    categoryKey: 'puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: TicTacToeGame,
    descriptionKey: 'tictactoe_desc',
    rulesKey: 'tictactoe_rules',
    historyKey: 'tictactoe_history',
    funFactsKey: ['tictactoe_fact1', 'tictactoe_fact2'],
  },
  {
    id: 'sudoku',
    nameKey: 'sudoku',
    categoryKey: 'puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: SudokuGame,
    descriptionKey: 'sudoku_desc',
    rulesKey: 'sudoku_rules',
    historyKey: 'sudoku_history',
    funFactsKey: ['sudoku_fact1', 'sudoku_fact2'],
    options: [{ id: 'difficulty', labelKey: 'difficulty_level', type: 'select', values: DIFF_OPTIONS, defaultValue: 'junior' }],
  },
  {
    id: 'wordmaster',
    nameKey: 'wordmaster',
    categoryKey: 'word',
    status: 'playable',
    enabled: true,
    visible: true,
    component: WordMasterGame,
    descriptionKey: 'wordmaster_desc',
    rulesKey: 'wordmaster_rules',
    historyKey: 'wordmaster_history',
    funFactsKey: ['wordmaster_fact1', 'wordmaster_fact2'],
  },
  {
    id: 'ludo',
    nameKey: 'ludo',
    categoryKey: 'board',
    status: 'playable',
    enabled: true,
    visible: true,
    component: LudoGame,
    descriptionKey: 'ludo_desc',
    rulesKey: 'ludo_rules',
    historyKey: 'ludo_history',
    funFactsKey: ['ludo_fact1'],
  },
  {
    id: 'snake',
    nameKey: 'snake',
    categoryKey: 'arcade',
    status: 'playable',
    enabled: true,
    visible: true,
    component: SnakeGame,
    descriptionKey: 'snake_desc',
    rulesKey: 'snake_rules',
    historyKey: 'snake_history',
    funFactsKey: ['snake_fact1'],
  },
  {
    id: 'pacman',
    nameKey: 'pacman',
    categoryKey: 'arcade',
    status: 'playable',
    enabled: true,
    visible: true,
    component: PacmanGame,
    descriptionKey: 'pacman_desc',
    rulesKey: 'pacman_rules',
    historyKey: 'pacman_history',
    funFactsKey: ['pacman_fact1'],
  },
  {
    id: 'tetris',
    nameKey: 'tetris',
    categoryKey: 'puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: TetrisGame,
    descriptionKey: 'tetris_desc',
    rulesKey: 'tetris_rules',
    historyKey: 'tetris_history',
    funFactsKey: ['tetris_fact1'],
  },
  {
    id: 'monopoly',
    nameKey: 'monopoly',
    categoryKey: 'board',
    status: 'playable',
    enabled: true,
    visible: true,
    component: MonopolyGame,
    descriptionKey: 'monopoly_desc',
    rulesKey: 'monopoly_rules',
    historyKey: 'monopoly_history',
    funFactsKey: ['monopoly_fact1'],
  },
  {
    id: 'hangman',
    nameKey: 'hangman',
    categoryKey: 'word',
    status: 'playable',
    enabled: true,
    visible: true,
    component: HangmanGame,
    descriptionKey: 'hangman_desc',
    rulesKey: 'hangman_rules',
    historyKey: 'hangman_history',
    funFactsKey: ['hangman_fact1'],
  },
  {
    id: '2048',
    nameKey: 'game2048',
    categoryKey: 'puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: Game2048,
    descriptionKey: '2048_desc',
    rulesKey: '2048_rules',
    historyKey: '2048_history',
    funFactsKey: ['2048_fact1'],
  },
  {
    id: 'uno',
    nameKey: 'uno',
    categoryKey: 'card',
    status: 'playable',
    enabled: true,
    visible: true,
    component: UnoGame,
    descriptionKey: 'uno_desc',
    rulesKey: 'uno_rules',
    historyKey: 'uno_history',
    funFactsKey: ['uno_fact1'],
  },
  {
    id: 'battleship',
    nameKey: 'battleship',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: BattleshipGame,
    descriptionKey: 'battleship_desc',
    rulesKey: 'battleship_rules',
    historyKey: 'battleship_history',
    funFactsKey: ['battleship_fact1'],
  },
  {
    id: 'scrabble',
    nameKey: 'scrabble',
    categoryKey: 'word',
    status: 'playable',
    enabled: true,
    visible: true,
    component: ScrabbleGame,
    descriptionKey: 'scrabble_desc',
    rulesKey: 'scrabble_rules',
    historyKey: 'scrabble_history',
    funFactsKey: ['scrabble_fact1'],
  },
  {
    id: 'clue',
    nameKey: 'clue',
    categoryKey: 'board',
    status: 'playable',
    enabled: true,
    visible: true,
    component: ClueGame,
    descriptionKey: 'clue_desc',
    rulesKey: 'clue_rules',
    historyKey: 'clue_history',
    funFactsKey: ['clue_fact1'],
  },
  {
    id: 'ticket_to_ride',
    nameKey: 'ticket_to_ride',
    categoryKey: 'board',
    status: 'playable',
    enabled: true,
    visible: true,
    component: TicketToRideGame,
    descriptionKey: 'ttr_desc',
    rulesKey: 'ttr_rules',
    historyKey: 'ttr_history',
    funFactsKey: ['ttr_fact1'],
  },
  {
    id: 'pandemic',
    nameKey: 'pandemic',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: PandemicGame,
    descriptionKey: 'pandemic_desc',
    rulesKey: 'pandemic_rules',
    historyKey: 'pandemic_history',
    funFactsKey: ['pandemic_fact1'],
  },
  {
    id: 'civ2',
    nameKey: 'civ2',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: Civ2Game,
    descriptionKey: 'civ2_desc',
    rulesKey: 'civ2_rules',
    historyKey: 'civ2_history',
    funFactsKey: ['civ2_fact1'],
  },
  {
    id: 'ksp',
    nameKey: 'ksp',
    categoryKey: 'arcade',
    status: 'playable',
    enabled: true,
    visible: true,
    component: KSPGame,
    descriptionKey: 'ksp_desc',
    rulesKey: 'ksp_rules',
    historyKey: 'ksp_history',
    funFactsKey: ['ksp_fact1'],
  },
  {
    id: 'racing',
    nameKey: 'racing',
    categoryKey: 'arcade',
    status: 'playable',
    enabled: true,
    visible: true,
    component: RacingGame,
    descriptionKey: 'racing_desc',
    rulesKey: 'racing_rules',
    historyKey: 'racing_history',
    funFactsKey: ['racing_fact1'],
  },
  {
    id: 'connect4',
    nameKey: 'connect4',
    categoryKey: 'strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: Connect4Game,
    descriptionKey: 'connect4_desc',
    rulesKey: 'connect4_rules',
    historyKey: 'connect4_history',
    funFactsKey: ['connect4_fact1'],
  },
];

const en = {
  'alile_play': 'Alile Play',
  'game_library': 'Library',
  'pricing': 'Pricing',
  'about': 'About',
  'feedback': 'Feedback',
  'feedback_title': 'Evaluation & Monitoring',
  'play_now': 'Play Now',
  'junior': 'Junior (K-6 Education)',
  'beginner': 'Beginner (Standard)',
  'intermediate': 'Intermediate (Logic Focus)',
  'advanced': 'Advanced (Mastery)',
  'difficulty_level': 'Difficulty Level',
  'rules': 'Rules',
  'history': 'History',
  'fun_facts': 'Fun Facts',
  'score': 'Score',
  'new_game': 'New Game',
  'reset_board': 'Reset Board',
  'game_over': 'Game Over!',
  'play_again': 'Play Again',
  'game_lobby': 'Game Lobby',
  'game_options': 'Options',
  'start_game': 'Start Game',
  'sudoku': 'Sudoku',
  'sudoku_desc': 'Logic-based number placement puzzle.',
  'sudoku_rules': 'Fill cells with numbers 1-9 (or 1-4 in Junior) such that each row, column, and subgrid contains every number exactly once.',
  'sudoku_history': 'Derived from "Number Place", popularized by Japanese publisher Nikoli in the 1980s.',
  'sudoku_fact1': 'The Junior level is specifically designed for Buford K-6 foundational logic curriculum.',
  'sudoku_fact2': 'There are 6,670,903,752,021,072,936,960 possible grids.',
  'pacman': 'Pac-Man',
  'pacman_desc': 'Arcade legend: Munch dots and dodge ghosts.',
  'pacman_rules': 'Eat all dots to clear the level. Avoid ghosts unless you eat a Power Pellet!',
  'pacman_history': 'Created by Toru Iwatani at Namco, released in 1980.',
  'pacman_fact1': 'Highest possible score is 3,333,360 points.',
  'snake': 'Snake',
  'snake_desc': 'Eat, grow, and avoid the boundaries.',
  'snake_rules': 'Use arrows or swipe. Eating food makes you longer. Do not touch your tail or the walls.',
  'snake_history': 'A mobile phenomenon since the Nokia 6110 in 1997.',
  'snake_fact1': 'The game speed scales with your current score.',
  'scrabble': 'Scrabble',
  'scrabble_desc': 'The ultimate word-building challenge.',
  'scrabble_rules': 'Build words horizontally or vertically. Words must connect to existing tiles. Use multipliers!',
  'scrabble_history': 'Invented by Alfred Mosher Butts in 1938.',
  'scrabble_fact1': 'Scrabble is played in over 120 countries.',
  'connect4': 'Connect 4',
  'connect4_desc': 'Drop discs to get four in a row.',
  'connect4_rules': 'Players take turns dropping colored discs into a vertical grid. Connect four horizontally, vertically, or diagonally.',
  'connect4_history': 'First published by Milton Bradley in 1974.',
  'connect4_fact1': 'There are 4,531,985,219,092 positions for all game boards.',
  'red': 'Red', 'blue': 'Blue', 'green': 'Green', 'yellow': 'Yellow',
  'strategy': 'Strategy', 'puzzle': 'Puzzle', 'arcade': 'Arcade', 'word': 'Word', 'board': 'Board', 'card': 'Card'
};

const fr = {
  'alile_play': 'Alile Play',
  'game_library': 'Bibliothèque',
  'pricing': 'Tarifs',
  'about': 'À Propos',
  'feedback': 'Avis',
  'feedback_title': 'Évaluation et Surveillance',
  'play_now': 'Jouer',
  'junior': 'Junior (K-6 Éducation)',
  'beginner': 'Débutant (Standard)',
  'intermediate': 'Intermédiaire (Logique)',
  'advanced': 'Advancé (Maîtrise)',
  'difficulty_level': 'Niveau de Difficulté',
  'rules': 'Règles',
  'history': 'Histoire',
  'fun_facts': 'Infos',
  'score': 'Score',
  'new_game': 'Nouveau Jeu',
  'reset_board': 'Réinitialiser',
  'game_over': 'Terminé !',
  'play_again': 'Rejouer',
  'game_lobby': 'Salon du Jeu',
  'start_game': 'Lancer le Jeu',
  'sudoku': 'Sudoku',
  'sudoku_desc': 'Casse-tête logique de placement de numéros.',
  'sudoku_rules': 'Remplissez la grille pour que chaque ligne, colonne et sous-grille contienne tous les chiffres sans répétition.',
  'pacman': 'Pac-Man',
  'snake': 'Serpent',
  'scrabble': 'Scrabble',
  'connect4': 'Puissance 4',
  'red': 'Rouge', 'blue': 'Bleu', 'green': 'Vert', 'yellow': 'Jaune',
};

const es = {
  'alile_play': 'Alile Play',
  'game_library': 'Biblioteca',
  'play_now': 'Jugar',
  'junior': 'Junior (K-6 Educación)',
  'sudoku': 'Sudoku',
  'pacman': 'Pac-Man',
  'snake': 'Serpiente',
  'scrabble': 'Scrabble',
  'connect4': 'Conecta 4',
};

const zh = {
  'alile_play': 'Alile Play',
  'game_library': '游戏库',
  'play_now': '现在开始',
  'junior': '初级 (K-6 教育)',
  'sudoku': '数独',
  'pacman': '吃豆人',
  'snake': '贪吃蛇',
  'scrabble': '拼字游戏',
  'connect4': '四连环',
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en, fr, es, de: { ...en }, zh, pt: { ...en },
};

export const DEFAULT_USER: User = {
  name: 'Guest Player',
  role: 'public',
  preferences: { theme: Theme.DARK, language: Language.EN, skillLevels: {} },
  subscription: { planId: 'free', gamesPlayedThisMonth: 0, gamePlays: {} },
};

export const PLANS: MonetizationPlan[] = [
  { id: 'free', nameKey: 'plan_free', price: 0, featuresKey: ['Access to 10 Basic Games', 'Limited Plays'], isFeatured: false },
  { id: 'pro', nameKey: 'plan_pro', price: 9, featuresKey: ['Access to All 22 Games', 'Unlimited Plays', 'AI Strategy Tips'], isFeatured: true },
];
