import { Game, Translations, ChatMessage } from './types';
import { ChessIcon, CheckersIcon, MonopolyIcon, PokerIcon, ScrabbleIcon, LudoIcon, UnoIcon, TetrisIcon, SudokuIcon, SolitaireIcon, GameControllerIcon } from './components/Icons';

export const GAMES: Game[] = [
    // Playable Games (Top 10)
    { id: 'chess', name: 'Chess', icon: ChessIcon, description: 'The classic game of strategy.', status: 'playable', category: 'classic_board' },
    { id: 'checkers', name: 'Checkers', icon: CheckersIcon, description: 'Jump and capture pieces.', status: 'playable', category: 'classic_board' },
    { id: 'monopoly', name: 'Monopoly', icon: MonopolyIcon, description: 'The real estate trading game.', status: 'playable', category: 'classic_board' },
    { id: 'poker', name: 'Poker', icon: PokerIcon, description: 'Texas Hold\'em and more.', status: 'playable', category: 'card_games' },
    { id: 'scrabble', name: 'Word Master', icon: ScrabbleIcon, description: 'The ultimate word game with AI analysis.', status: 'playable', category: 'puzzle_games' },
    { id: 'ludo', name: 'Ludo', icon: LudoIcon, description: 'Race your tokens to the finish.', status: 'playable', category: 'classic_board' },
    { id: 'uno', name: 'Uno', icon: UnoIcon, description: 'Match colors and numbers.', status: 'playable', category: 'card_games' },
    { id: 'tetris', name: 'Tetris', icon: TetrisIcon, description: 'Fit the falling blocks.', status: 'playable', category: 'puzzle_games' },
    { id: 'sudoku', name: 'Sudoku', icon: SudokuIcon, description: 'The number placement puzzle.', status: 'playable', category: 'puzzle_games', options: [
        { label: 'easy_9x9', value: '9x9_easy' },
        { label: 'medium_9x9', value: '9x9_medium' },
        { label: 'grand_master_16x16', value: '16x16_hard' },
    ]},
    { id: 'solitaire', name: 'Solitaire', icon: SolitaireIcon, description: 'Classic card sorting.', status: 'playable', category: 'card_games' },

    // Coming Soon Games
    { id: 'connect4', name: 'Connect 4', icon: GameControllerIcon, description: 'Get four in a row.', status: 'coming-soon', category: 'classic_board', options: [
        { label: 'Standard (6x7)', value: '6x7' },
        { label: 'Large (8x8)', value: '8x8' },
        { label: 'For Kids (5x4)', value: '5x4' },
    ]},
    { id: 'mahjong', name: 'Mahjong', icon: GameControllerIcon, description: 'A tile-based game.', status: 'coming-soon', category: 'classic_board' },
    { id: 'backgammon', name: 'Backgammon', icon: GameControllerIcon, description: 'One of the oldest board games.', status: 'coming-soon', category: 'classic_board' },
    { id: 'go', name: 'Go', icon: GameControllerIcon, description: 'An abstract strategy board game.', status: 'coming-soon', category: 'strategy' },
    { id: 'risk', name: 'Risk', icon: GameControllerIcon, description: 'A game of global domination.', status: 'coming-soon', category: 'strategy' },
    { id: 'catan', name: 'Catan', icon: GameControllerIcon, description: 'Trade, build, settle.', status: 'coming-soon', category: 'strategy' },
    { id: 'dominoes', name: 'Dominoes', icon: GameControllerIcon, description: 'Match tiles with the same number.', status: 'coming-soon', category: 'classic_board' },
    { id: 'yahtzee', name: 'Yahtzee', icon: GameControllerIcon, description: 'A classic dice game.', status: 'coming-soon', category: 'classic_board' },
    { id: 'battleship', name: 'Battleship', icon: GameControllerIcon, description: 'Sink your opponent\'s fleet.', status: 'coming-soon', category: 'strategy' },
    { id: 'jenga', name: 'Jenga', icon: GameControllerIcon, description: 'Don\'t let the tower fall.', status: 'coming-soon', category: 'modern_classics' },
    { id: 'hearts', name: 'Hearts', icon: GameControllerIcon, description: 'Avoid taking hearts.', status: 'coming-soon', category: 'card_games' },
    { id: 'spades', name: 'Spades', icon: GameControllerIcon, description: 'A trick-taking card game.', status: 'coming-soon', category: 'card_games' },
    { id: 'bridge', name: 'Bridge', icon: GameControllerIcon, description: 'The ultimate partnership card game.', status: 'coming-soon', category: 'card_games' },
    { id: 'euchre', name: 'Euchre', icon: GameControllerIcon, description: 'A trick-taking card game.', status: 'coming-soon', category: 'card_games' },
    { id: 'ginrummy', name: 'Gin Rummy', icon: GameControllerIcon, description: 'A classic card matching game.', status: 'coming-soon', category: 'card_games' },
    { id: 'tichu', name: 'Tichu', icon: GameControllerIcon, description: 'A climbing card game.', status: 'coming-soon', category: 'card_games' },
    { id: 'clue', name: 'Clue', icon: GameControllerIcon, description: 'Solve the mystery.', status: 'coming-soon', category: 'modern_classics' },
    { id: 'starcraft', name: 'StarCraft', icon: GameControllerIcon, description: 'A real-time strategy classic.', status: 'coming-soon', category: 'digital_strategy' },
    { id: 'warcraft', name: 'Warcraft', icon: GameControllerIcon, description: 'Fantasy RTS.', status: 'coming-soon', category: 'digital_strategy' },
    { id: 'dota', name: 'Dota 2', icon: GameControllerIcon, description: 'A multiplayer online battle arena.', status: 'coming-soon', category: 'digital_strategy' },
    { id: 'league', name: 'League of Legends', icon: GameControllerIcon, description: 'A popular MOBA.', status: 'coming-soon', category: 'digital_strategy' },
    { id: 'csgo', name: 'Counter-Strike', icon: GameControllerIcon, description: 'Tactical first-person shooter.', status: 'coming-soon', category: 'digital_strategy' },
    { id: 'valorant', name: 'Valorant', icon: GameControllerIcon, description: '5v5 character-based tactical shooter.', status: 'coming-soon', category: 'digital_strategy' },
    { id: 'fortnite', name: 'Fortnite', icon: GameControllerIcon, description: 'A battle royale game.', status: 'coming-soon', category: 'digital_strategy' },
    { id: 'minecraft', name: 'Minecraft', icon: GameControllerIcon, description: 'Build and explore.', status: 'coming-soon', category: 'simulation_creative' },
    { id: 'roblox', name: 'Roblox', icon: GameControllerIcon, description: 'A global platform to play and create.', status: 'coming-soon', category: 'simulation_creative' },
    { id: 'amongus', name: 'Among Us', icon: GameControllerIcon, description: 'A game of teamwork and betrayal.', status: 'coming-soon', category: 'modern_classics' },
    { id: 'fallguys', name: 'Fall Guys', icon: GameControllerIcon, description: 'A massively multiplayer party game.', status: 'coming-soon', category: 'modern_classics' },
    { id: 'stardew', name: 'Stardew Valley', icon: GameControllerIcon, description: 'A farming simulation RPG.', status: 'coming-soon', category: 'simulation_creative' },
    { id: 'terraria', name: 'Terraria', icon: GameControllerIcon, description: 'A 2D action-adventure sandbox game.', status: 'coming-soon', category: 'simulation_creative' },
    { id: 'hearthstone', name: 'Hearthstone', icon: GameControllerIcon, description: 'A digital collectible card game.', status: 'coming-soon', category: 'card_games' },
    { id: 'gwent', name: 'Gwent', icon: GameControllerIcon, description: 'The Witcher Card Game.', status: 'coming-soon', category: 'card_games' },
    { id: 'mtg', name: 'Magic: The Gathering', icon: GameControllerIcon, description: 'The original trading card game.', status: 'coming-soon', category: 'card_games' },
    { id: 'pokemon', name: 'Pokémon TCG', icon: GameControllerIcon, description: 'Trade and battle with Pokémon cards.', status: 'coming-soon', category: 'card_games' },
    { id: 'yugioh', name: 'Yu-Gi-Oh!', icon: GameControllerIcon, description: 'It\'s time to duel!', status: 'coming-soon', category: 'card_games' },
    { id: 'civilization', name: 'Civilization VI', icon: GameControllerIcon, description: 'Build an empire to stand the test of time.', status: 'coming-soon', category: 'strategy' },
    { id: 'sims', name: 'The Sims 4', icon: GameControllerIcon, description: 'Create and control people.', status: 'coming-soon', category: 'simulation_creative' },
    { id: 'animalcrossing', name: 'Animal Crossing', icon: GameControllerIcon, description: 'Create your own island paradise.', status: 'coming-soon', category: 'simulation_creative' },
    { id: 'fifa', name: 'FIFA 23', icon: GameControllerIcon, description: 'The world\'s game.', status: 'coming-soon', category: 'modern_classics' },
    { id: 'nba2k', name: 'NBA 2K23', icon: GameControllerIcon, description: 'Realistic basketball simulation.', status: 'coming-soon', category: 'modern_classics' },
];

export const MOCK_LEADERBOARD = [
    { id: 1, name: 'PlayerOne', score: 150230 },
    { id: 2, name: 'ChessMaster', score: 145890 },
    { id: 3, name: 'LadyLuck', score: 139120 },
    { id: 4, name: 'Rookie', score: 120500 },
    { id: 5, name: 'Strategist', score: 115670 },
];

export const MOCK_CHAT: ChatMessage[] = [
    { id: 1, user: 'PlayerOne', text: 'Good game everyone!', isFlagged: false },
    { id: 2, user: 'Rookie', text: 'You too! That was close.', isFlagged: false },
    { id: 3, user: 'BadSport', text: 'You got lucky, I will crush you next time.', isFlagged: true },
    { id: 4, user: 'ChessMaster', text: 'Let\'s keep it friendly.', isFlagged: false },
];

export const MOCK_ANALYTICS_DATA = [
    { name: 'Mon', players: 4000, revenue: 2400 },
    { name: 'Tue', players: 3000, revenue: 1398 },
    { name: 'Wed', players: 2000, revenue: 9800 },
    { name: 'Thu', players: 2780, revenue: 3908 },
    { name: 'Fri', players: 1890, revenue: 4800 },
    { name: 'Sat', players: 2390, revenue: 3800 },
    { name: 'Sun', players: 3490, revenue: 4300 },
];

export const AI_CREW = [
    { id: 'mod', name: 'Community Moderator' },
    { id: 'support', name: 'Support Agent' },
    { id: 'marketing', name: 'Marketing & Sales' },
    { id: 'brand', name: 'Brand Management' },
];


export const TRANSLATIONS: Translations = {
    welcome: {
        en: 'Alileva Gaming Dashboard',
        es: 'Panel de Juegos Alileva',
        fr: 'Tableau de Bord de Jeu Alileva',
        zh: 'Alileva 游戏仪表板',
    },
    select_game: {
        en: 'Select a Game',
        es: 'Selecciona un Juego',
        fr: 'Sélectionnez un Jeu',
        zh: '选择一个游戏',
    },
    leaderboard: {
        en: 'Leaderboard',
        es: 'Tabla de Posiciones',
        fr: 'Classement',
        zh: '排行榜',
    },
    live_chat: {
        en: 'Live Chat',
        es: 'Chat en Vivo',
        fr: 'Chat en Direct',
        zh: '实时聊天',
    },
    flagged_by_ai: {
        en: 'Flagged by AI Moderator for aggression.',
        es: 'Marcado por el Moderador de IA por agresión.',
        fr: 'Signalé par le modérateur IA pour agression.',
        zh: '被AI版主标记为攻击性言论。',
    },
    platform_analytics: {
        en: 'Platform Analytics',
        es: 'Análisis de la Plataforma',
        fr: 'Analyses de la Plateforme',
        zh: '平台分析',
    },
    players: {
        en: 'Active Players',
        es: 'Jugadores Activos',
        fr: 'Joueurs Actifs',
        zh: '活跃玩家',
    },
    revenue: {
        en: 'Daily Revenue ($)',
        es: 'Ingresos Diarios ($)',
        fr: 'Revenu Quotidien ($)',
        zh: '每日收入 ($)',
    },
    platform_management: {
        en: 'Platform Management',
        es: 'Gestión de la Plataforma',
        fr: 'Gestion de la Plateforme',
        zh: '平台管理',
    },
    ai_crew_status: {
        en: 'AI Crew Status',
        es: 'Estado del Equipo de IA',
        fr: "Statut de l'Équipe IA",
        zh: 'AI团队状态',
    },
    online: {
        en: 'Online',
        es: 'En Línea',
        fr: 'En Ligne',
        zh: '在线',
    },
    monetization: {
        en: 'Monetization',
        es: 'Monetización',
        fr: 'Monétisation',
        zh: '盈利',
    },
    plan: {
        en: 'Current Plan',
        es: 'Plan Actual',
        fr: 'Plan Actuel',
        zh: '当前计划',
    },
    ads_revenue: {
        en: 'Ads Revenue (Today)',
        es: 'Ingresos por Anuncios (Hoy)',
        fr: 'Revenus Publicitaires (Aujourd\'hui)',
        zh: '今日广告收入',
    },
    manage_subscription: {
        en: 'Manage Subscription',
        es: 'Gestionar Suscripción',
        fr: 'Gérer l\'Abonnement',
        zh: '管理订阅',
    },
    white_label: {
        en: 'White-Label & Partnerships',
        es: 'Marca Blanca y Asociaciones',
        fr: 'Marque Blanche & Partenariats',
        zh: '白标与合作',
    },
    white_label_desc: {
        en: 'Deploy our platform under your brand. Ideal for airlines, hotels, and transport companies.',
        es: 'Implemente nuestra plataforma bajo su marca. Ideal para aerolíneas, hoteles y empresas de transporte.',
        fr: 'Déployez notre plateforme sous votre marque. Idéal pour les compagnies aériennes, les hôtels et les entreprises de transport.',
        zh: '在您的品牌下部署我们的平台。非常适合航空公司、酒店和运输公司。',
    },
    learn_more: {
        en: 'Learn More',
        es: 'Aprende Más',
        fr: 'En Savoir Plus',
        zh: '了解更多',
    },
    affiliate_program: {
        en: 'Affiliate Program',
        es: 'Programa de Afiliados',
        fr: 'Programme d\'Affiliation',
        zh: '联盟计划',
    },
    affiliate_desc: {
        en: 'Earn revenue by referring new players and partners to the Alileva platform.',
        es: 'Gane ingresos refiriendo nuevos jugadores y socios a la plataforma Alileva.',
        fr: 'Générez des revenus en référant de nouveaux joueurs et partenaires à la plateforme Alileva.',
        zh: '通过推荐新玩家和合作伙伴到Alileva平台来赚取收入。',
    },
    join_now: {
        en: 'Join Now',
        es: 'Únete Ahora',
        fr: 'Rejoignez Maintenant',
        zh: '立即加入',
    },
    deployment_options: {
        en: 'Deployment Options',
        es: 'Opciones de Implementación',
        fr: 'Options de Déploiement',
        zh: '部署选项',
    },
    deployment_desc: {
        en: 'Flexible deployment across multiple platforms to reach users everywhere.',
        es: 'Implementación flexible en múltiples plataformas para llegar a usuarios en todas partes.',
        fr: 'Déploiement flexible sur plusieurs plateformes pour atteindre les utilisateurs partout.',
        zh: '跨多个平台的灵活部署，覆盖各处用户。',
    },
    user_verification: {
        en: 'User Verification Status',
        es: 'Estado de Verificación de Usuario',
        fr: "Statut de Vérification de l'Utilisateur",
        zh: '用户验证状态',
    },
    provide_feedback: {
        en: 'Provide Feedback',
        es: 'Enviar Comentarios',
        fr: 'Donner un Avis',
        zh: '提供反馈',
    },
    your_feedback: {
        en: 'Your feedback...',
        es: 'Tus comentarios...',
        fr: 'Vos commentaires...',
        zh: '您的反馈...',
    },
    submit: {
        en: 'Submit',
        es: 'Enviar',
        fr: 'Soumettre',
        zh: '提交',
    },
    submitting: {
        en: 'Submitting...',
        es: 'Enviando...',
        fr: 'Envoi en cours...',
        zh: '提交中...',
    },
    feedback_received: {
        en: 'Thank you for your feedback!',
        es: '¡Gracias por tus comentarios!',
        fr: 'Merci pour vos commentaires!',
        zh: '感谢您的反馈！',
    },
    type_message: {
        en: 'Type a message...',
        es: 'Escribe un mensaje...',
        fr: 'Écrire un message...',
        zh: '输入消息...',
    },
    send: {
        en: 'Send',
        es: 'Enviar',
        fr: 'Envoyer',
        zh: '发送',
    },
    play: {
        en: 'Play',
        es: 'Jugar',
        fr: 'Jouer',
        zh: '玩',
    },
    options: {
        en: 'Options',
        es: 'Opciones',
        fr: 'Options',
        zh: '选项',
    },
    coming_soon: {
        en: 'Coming Soon',
        es: 'Próximamente',
        fr: 'Bientôt Disponible',
        zh: '即将推出',
    },
    select_option: {
        en: 'Select Option',
        es: 'Seleccionar Opción',
        fr: 'Sélectionner une Option',
        zh: '选择选项',
    },
    start_game: {
        en: 'Start Game',
        es: 'Empezar Juego',
        fr: 'Commencer le Jeu',
        zh: '开始游戏',
    },
    cancel: {
        en: 'Cancel',
        es: 'Cancelar',
        fr: 'Annuler',
        zh: '取消',
    },
    // Sudoku Options
    easy_9x9: { en: 'Easy (9x9)', es: 'Fácil (9x9)', fr: 'Facile (9x9)', zh: '简单 (9x9)' },
    medium_9x9: { en: 'Medium (9x9)', es: 'Medio (9x9)', fr: 'Moyen (9x9)', zh: '中等 (9x9)' },
    grand_master_16x16: { en: 'Grand Master (16x16)', es: 'Gran Maestro (16x16)', fr: 'Grand Maître (16x16)', zh: '大师 (16x16)' },
    // Game Categories
    classic_board: { en: 'Classic Board Games', es: 'Juegos de Mesa Clásicos', fr: 'Jeux de Société Classiques', zh: '经典棋盘游戏' },
    strategy: { en: 'Strategy Games', es: 'Juegos de Estrategia', fr: 'Jeux de Stratégie', zh: '策略游戏' },
    card_games: { en: 'Card Games', es: 'Juegos de Cartas', fr: 'Jeux de Cartes', zh: '纸牌游戏' },
    puzzle_games: { en: 'Puzzle Games', es: 'Juegos de Puzzle', fr: 'Jeux de Puzzle', zh: '益智游戏' },
    modern_classics: { en: 'Modern Classics', es: 'Clásicos Modernos', fr: 'Classiques Modernes', zh: '现代经典' },
    digital_strategy: { en: 'Digital Strategy & MOBAs', es: 'Estrategia Digital y MOBAs', fr: 'Stratégie Numérique & MOBAs', zh: '数字策略和MOBA' },
    simulation_creative: { en: 'Simulation & Creative', es: 'Simulación y Creatividad', fr: 'Simulation & Créatif', zh: '模拟与创造' },

    // Game UI
    back_to_dashboard: { en: 'Back to Dashboard', es: 'Volver al Panel', fr: 'Retour au Tableau de Bord', zh: '返回仪表板' },
    score: { en: 'Score', es: 'Puntuación', fr: 'Score', zh: '分数' },
    level: { en: 'Level', es: 'Nivel', fr: 'Niveau', zh: '等级' },
    lines: { en: 'Lines', es: 'Líneas', fr: 'Lignes', zh: '行数' },
    next: { en: 'Next', es: 'Siguiente', fr: 'Prochain', zh: '下一个' },
    game_over: { en: 'Game Over', es: 'Juego Terminado', fr: 'Partie Terminée', zh: '游戏结束' },
    play_again: { en: 'Play Again', es: 'Jugar de Nuevo', fr: 'Rejouer', zh: '再玩一次' },
    sudoku_instructions: { en: 'Fill the grid. No number repeats in any row, column or subgrid.', es: 'Llena la cuadrícula. Ningún número se repite en ninguna fila, columna o subcuadrícula.', fr: 'Remplissez la grille. Aucun numéro ne se répète dans une ligne, colonne ou sous-grille.', zh: '填充所有格子。每行、每列、每宫的数字都不能重复。' },
    sudoku_error: { en: 'Invalid move. Check for conflicts.', es: 'Movimiento inválido. Revisa los conflictos.', fr: 'Mouvement invalide. Vérifiez les conflits.', zh: '无效的移动。请检查冲突。' },

    
    // Word Master AI Coach
    ai_word_coach: { en: 'AI Word Coach', es: 'Entrenador de Palabras IA', fr: 'Coach de Mots IA', zh: 'AI 单词教练' },
    analyze_word: { en: 'Analyze Word', es: 'Analizar Palabra', fr: 'Analyser le Mot', zh: '分析单词' },
    get_suggestion: { en: 'Get Suggestion', es: 'Obtener Sugerencia', fr: 'Obtenir une Suggestion', zh: '获取建议' },
    your_tiles: { en: 'Your Tiles', es: 'Tus Fichas', fr: 'Vos Tuiles', zh: '你的字母' },
    detail_level: { en: 'Detail Level', es: 'Nivel de Detalle', fr: 'Niveau de Détail', zh: '详细程度' },
    basic: { en: 'Basic', es: 'Básico', fr: 'Basique', zh: '基本' },
    full_analysis: { en: 'Full Analysis', es: 'Análisis Completo', fr: 'Analyse Complète', zh: '全面分析' },
    definition: { en: 'Definition', es: 'Definición', fr: 'Définition', zh: '定义' },
    synonyms: { en: 'Synonyms', es: 'Sinónimos', fr: 'Synonymes', zh: '同义词' },
    antonyms: { en: 'Antonyms', es: 'Antónimos', fr: 'Antonymes', zh: '反义词' },
    example: { en: 'Example', es: 'Ejemplo', fr: 'Exemple', zh: '例子' },
    etymology: { en: 'Etymology', es: 'Etimología', fr: 'Étymologie', zh: '词源' },
    ai_suggestion: { en: 'AI Suggestion', es: 'Sugerencia de IA', fr: 'Suggestion de l\'IA', zh: 'AI 建议' },
    word: { en: 'Word', es: 'Palabra', fr: 'Mot', zh: '单词' },
    points: { en: 'Points', es: 'Puntos', fr: 'Points', zh: '分数' },
    word_not_possible: { en: 'Word cannot be made from your tiles.', es: 'La palabra no se puede formar con tus fichas.', fr: 'Le mot ne peut pas être formé avec vos tuiles.', zh: '无法用您的字母组成该单词。' },
};