import type { Game, MonetizationPlan, User } from './types';
import { Language, Theme, SkillLevel } from './types';
import ChessGame from './features/games/chess/ChessGame';
import CheckersGame from './features/games/checkers/CheckersGame';
import TicTacToeGame from './features/games/tic-tac-toe/TicTacToeGame';
import SudokuGame from './features/games/sudoku/SudokuGame';
import WordMasterGame from './features/games/wordmaster/WordMasterGame';
import PacmanGame from './features/games/pacman/PacmanGame';
import TetrisGame from './features/games/tetris/TetrisGame';
import MonopolyGame from './features/games/monopoly/MonopolyGame';
import LudoGame from './features/games/ludo/LudoGame';
import HangmanGame from './features/games/hangman/HangmanGame';
import Game2048 from './features/games/2048/Game2048';
import UnoGame from './features/games/uno/UnoGame';


export const GAMES: Game[] = [
  {
    id: 'chess',
    nameKey: 'game_chess_name',
    categoryKey: 'game_category_strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: ChessGame,
    descriptionKey: 'game_chess_desc',
    rulesKey: 'game_chess_rules',
    historyKey: 'game_chess_history',
    funFactsKey: ['game_chess_fact1', 'game_chess_fact2', 'game_chess_fact3'],
    options: [
      { id: 'difficulty', labelKey: 'option_difficulty', type: 'select', 
        values: [
          { value: SkillLevel.BEGINNER, labelKey: 'skill_beginner' },
          { value: SkillLevel.INTERMEDIATE, labelKey: 'skill_intermediate' },
          { value: SkillLevel.ADVANCED, labelKey: 'skill_advanced' },
        ],
        defaultValue: SkillLevel.INTERMEDIATE
      }
    ],
  },
  {
    id: 'checkers',
    nameKey: 'game_checkers_name',
    categoryKey: 'game_category_strategy',
    status: 'playable',
    enabled: true,
    visible: true,
    component: CheckersGame,
    descriptionKey: 'game_checkers_desc',
    rulesKey: 'game_checkers_rules',
    historyKey: 'game_checkers_history',
    funFactsKey: ['game_checkers_fact1', 'game_checkers_fact2'],
  },
  {
    id: 'tic-tac-toe',
    nameKey: 'game_tictactoe_name',
    categoryKey: 'game_category_puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: TicTacToeGame,
    descriptionKey: 'game_tictactoe_desc',
    rulesKey: 'game_tictactoe_rules',
    historyKey: 'game_tictactoe_history',
    funFactsKey: ['game_tictactoe_fact1'],
  },
  {
    id: 'sudoku',
    nameKey: 'game_sudoku_name',
    categoryKey: 'game_category_puzzle',
    status: 'playable',
    enabled: true,
    visible: true,
    component: SudokuGame,
    descriptionKey: 'game_sudoku_desc',
    rulesKey: 'game_sudoku_rules',
    historyKey: 'game_sudoku_history',
    funFactsKey: ['game_sudoku_fact1', 'game_sudoku_fact2'],
    options: [
      { id: 'difficulty', labelKey: 'option_difficulty_level', type: 'select', 
        values: [
          { value: 'easy', labelKey: 'skill_easy' },
          { value: 'medium', labelKey: 'skill_medium' },
          { value: 'hard', labelKey: 'skill_hard' },
        ],
        defaultValue: 'medium'
      }
    ]
  },
  {
    id: 'wordmaster',
    nameKey: 'game_wordmaster_name',
    categoryKey: 'game_category_word',
    status: 'playable',
    enabled: true,
    visible: true,
    component: WordMasterGame,
    descriptionKey: 'game_wordmaster_desc',
    rulesKey: 'game_wordmaster_rules',
    historyKey: 'game_wordmaster_history',
    funFactsKey: ['game_wordmaster_fact1', 'game_wordmaster_fact2'],
  },
  {
    id: 'pacman',
    nameKey: 'game_pacman_name',
    categoryKey: 'game_category_arcade',
    status: 'coming_soon',
    enabled: true,
    visible: true,
    component: PacmanGame,
    descriptionKey: 'game_pacman_desc',
    rulesKey: 'game_pacman_rules',
    historyKey: 'game_pacman_history',
    funFactsKey: ['game_pacman_fact1'],
  },
  {
    id: 'tetris',
    nameKey: 'game_tetris_name',
    categoryKey: 'game_category_puzzle',
    status: 'coming_soon',
    enabled: true,
    visible: true,
    component: TetrisGame,
    descriptionKey: 'game_tetris_desc',
    rulesKey: 'game_tetris_rules',
    historyKey: 'game_tetris_history',
    funFactsKey: ['game_tetris_fact1'],
  },
    {
    id: 'monopoly',
    nameKey: 'game_monopoly_name',
    categoryKey: 'game_category_board_card',
    status: 'coming_soon',
    enabled: true,
    visible: true,
    component: MonopolyGame,
    descriptionKey: 'game_monopoly_desc',
    rulesKey: 'game_monopoly_rules',
    historyKey: 'game_monopoly_history',
    funFactsKey: ['game_monopoly_fact1'],
  },
  {
    id: 'ludo',
    nameKey: 'game_ludo_name',
    categoryKey: 'game_category_board_card',
    status: 'coming_soon',
    enabled: true,
    visible: true,
    component: LudoGame,
    descriptionKey: 'game_ludo_desc',
    rulesKey: 'game_ludo_rules',
    historyKey: 'game_ludo_history',
    funFactsKey: ['game_ludo_fact1'],
  },
  {
    id: 'hangman',
    nameKey: 'game_hangman_name',
    categoryKey: 'game_category_word',
    status: 'coming_soon',
    enabled: true,
    visible: true,
    component: HangmanGame,
    descriptionKey: 'game_hangman_desc',
    rulesKey: 'game_hangman_rules',
    historyKey: 'game_hangman_history',
    funFactsKey: ['game_hangman_fact1'],
  },
  {
    id: '2048',
    nameKey: 'game_2048_name',
    categoryKey: 'game_category_puzzle',
    status: 'coming_soon',
    enabled: true,
    visible: true,
    component: Game2048,
    descriptionKey: 'game_2048_desc',
    rulesKey: 'game_2048_rules',
    historyKey: 'game_2048_history',
    funFactsKey: ['game_2048_fact1'],
  },
  {
    id: 'uno',
    nameKey: 'game_uno_name',
    categoryKey: 'game_category_board_card',
    status: 'coming_soon',
    enabled: true,
    visible: true,
    component: UnoGame,
    descriptionKey: 'game_uno_desc',
    rulesKey: 'game_uno_rules',
    historyKey: 'game_uno_history',
    funFactsKey: ['game_uno_fact1'],
  },
];

const en = {
    // General
    'alile_play': 'Alile Play',
    'game_library': 'Game Library',
    'pricing': 'Pricing',
    'coming_soon': 'Coming Soon',
    'play_now': 'Play Now',
    'back_to_library': 'Back to Library',
    'start_game': 'Start Game',
    'game_lobby': 'Game Lobby',
    'rules': 'Rules',
    'history': 'History',
    'fun_facts': 'Fun Facts',
    'game_options': 'Game Options',
    'select_level': 'Select your level',
    'skill_beginner': 'Beginner',
    'skill_intermediate': 'Intermediate',
    'skill_advanced': 'Advanced',
    'skill_easy': 'Easy',
    'skill_medium': 'Medium',
    'skill_hard': 'Hard',
    'option_difficulty': 'AI Difficulty',
    'option_difficulty_level': 'Difficulty Level',
    'ai_chat_placeholder': 'Ask Alile AI...',
    'ai_chat_title': 'Alile AI Assistant',
    'error_boundary_title': 'Oops! Something went wrong.',
    'error_boundary_message': 'An unexpected error occurred. Please refresh the page to continue.',
    'new_game': 'New Game',
    'reset_board': 'Reset Board',
    'featured_plan': 'Featured',
    'btn_select_plan': 'Select Plan',

    // Categories
    'game_category_strategy': 'Strategy',
    'game_category_puzzle': 'Puzzle',
    'game_category_word': 'Word',
    'game_category_arcade': 'Arcade',
    'game_category_board_card': 'Board & Card',
    
    // Chess
    'game_chess_name': 'Chess',
    'game_chess_desc': 'The ultimate game of strategy and intellect. Checkmate the opponent\'s king to win.',
    'game_chess_rules': 'Each player starts with 16 pieces. The objective is to checkmate the opponent\'s king. Each piece type moves in a different way.',
    'game_chess_history': 'Originating in India in the 6th century, chess spread to Persia and the Muslim world before reaching Europe.',
    'game_chess_fact1': 'The longest chess game theoretically possible is 5,949 moves.',
    'game_chess_fact2': 'The word "Checkmate" comes from the Persian phrase "Shah Mat," meaning "the King is dead."',
    'game_chess_fact3': 'A grandmaster\'s brain is a marvel of pattern recognition, able to recall tens of thousands of game positions.',
    'chess_turn_your': 'Your Turn',
    'chess_turn_ai': 'AI\'s Turn',
    'chess_check': 'Check!',
    'chess_checkmate': 'Checkmate!',
    'chess_draw': 'Draw!',

    // Checkers
    'game_checkers_name': 'Checkers',
    'game_checkers_desc': 'A classic board game where players jump over opponent pieces to capture them.',
    'game_checkers_rules': 'Move your pieces diagonally forward. Capture opponent pieces by jumping over them. Reach the other side to become a King.',
    'game_checkers_history': 'A form of checkers was played by the ancient Egyptians.',
    'game_checkers_fact1': 'The number of possible positions in checkers is about 500 quintillion.',
    'game_checkers_fact2': 'The world\'s first checkers computer program was written in 1952.',

    // Tic-Tac-Toe
    'game_tictactoe_name': 'Tic-Tac-Toe',
    'game_tictactoe_desc': 'A simple but classic game of getting three in a row.',
    'game_tictactoe_rules': 'Players take turns marking spaces in a 3×3 grid. The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row wins.',
    'game_tictactoe_history': 'An early variant of Tic-Tac-Toe was played in the Roman Empire, around the first century BC.',
    'game_tictactoe_fact1': 'A perfect Tic-Tac-Toe game always ends in a draw.',

    // Sudoku
    'game_sudoku_name': 'Sudoku',
    'game_sudoku_desc': 'A logic-based number-placement puzzle.',
    'game_sudoku_rules': 'Fill a 9x9 grid so that each column, each row, and each of the nine 3x3 subgrids contain all of the digits from 1 to 9.',
    'game_sudoku_history': 'The modern version of Sudoku was invented in the United States in 1979, but became popular in Japan in the 1980s.',
    'game_sudoku_fact1': 'There are 6,670,903,752,021,072,936,960 possible Sudoku grids.',
    'game_sudoku_fact2': 'The name Sudoku is a Japanese abbreviation for "Su-ji wa dokushin ni kagiru", which means "the numbers must be single".',
    'sudoku_congrats': 'Congratulations!',
    'sudoku_solved': 'You solved the puzzle!',

    // Word Master
    'game_wordmaster_name': 'Word Master',
    'game_wordmaster_desc': 'Guess the secret five-letter word in six tries.',
    'game_wordmaster_rules': 'Each guess must be a valid five-letter word. Hit enter to submit. After each guess, the color of the tiles will change to show how close your guess was to the word. Green is a correct letter in the correct spot. Yellow is a correct letter in the wrong spot. Gray is a letter not in the word.',
    'game_wordmaster_history': 'Inspired by the classic pen-and-paper game Jotto and the TV game show Lingo, it exploded in popularity as "Wordle" in the early 2020s.',
    'game_wordmaster_fact1': 'The most common starting letter for five-letter words in English is \'S\'.',
    'game_wordmaster_fact2': 'Commonly used vowels like A, E, I, O, U are crucial for solving the puzzle quickly.',
    'wordmaster_win': 'You got it!',
    'wordmaster_lose': 'Nice try! The word was:',
    'wordmaster_invalid_word': 'Not a valid word',

    // Pac-Man
    'game_pacman_name': 'Pac-Man',
    'game_pacman_desc': 'Navigate a maze, eat all the dots, and avoid the ghosts!',
    'game_pacman_rules': 'Control Pac-Man to eat all the pac-dots in the maze. Avoid Blinky, Pinky, Inky, and Clyde. Eating a Power Pellet lets you eat the ghosts for a short time.',
    'game_pacman_history': 'Released by Namco in 1980, it became a worldwide phenomenon and an icon of 80s pop culture.',
    'game_pacman_fact1': 'The highest possible score in the original Pac-Man arcade game is 3,333,360 points.',

    // Tetris
    'game_tetris_name': 'Tetris',
    'game_tetris_desc': 'The iconic falling block puzzle game. Clear lines to score points.',
    'game_tetris_rules': 'Rotate and move falling blocks (Tetriminos) to create solid horizontal lines. When a line is complete, it disappears, and you score points.',
    'game_tetris_history': 'Created in 1984 by Soviet software engineer Alexey Pajitnov, Tetris has been ported to almost every computer and console imaginable.',
    'game_tetris_fact1': 'Playing Tetris can increase the thickness of your brain\'s cortex.',
    
    // Monopoly
    'game_monopoly_name': 'Monopoly',
    'game_monopoly_desc': 'The classic real estate trading game. Bankrupt your opponents to win!',
    'game_monopoly_rules': 'Roll the dice, move around the board, and buy properties. Collect rent from opponents and build houses and hotels to increase your income.',
    'game_monopoly_history': 'Originally based on "The Landlord\'s Game" by Elizabeth Magie in 1903, it was first published by Parker Brothers in 1935.',
    'game_monopoly_fact1': 'The longest Monopoly game ever played lasted for 70 straight days.',
    
    // Ludo
    'game_ludo_name': 'Ludo',
    'game_ludo_desc': 'A classic race-to-the-finish board game for two to four players.',
    'game_ludo_rules': 'Players race their four tokens from start to finish according to the rolls of a single die. Be the first to get all your tokens home.',
    'game_ludo_history': 'Ludo is a simplified version of the ancient Indian game Pachisi, which dates back to the 6th century.',
    'game_ludo_fact1': 'The name "Ludo" comes from the Latin word for "I play".',

    // Hangman
    'game_hangman_name': 'Hangman',
    'game_hangman_desc': 'The classic word-guessing game. Find the word before it\'s too late!',
    'game_hangman_rules': 'One player thinks of a word, and the other(s) tries to guess it by suggesting letters within a certain number of guesses.',
    'game_hangman_history': 'The game is mentioned in books of traditional games from the late 19th century.',
    'game_hangman_fact1': 'The most difficult words for hangman often include letters like J, Q, X, and Z.',

    // 2048
    'game_2048_name': '2048',
    'game_2048_desc': 'A sliding tile puzzle game. Combine tiles to reach the 2048 tile.',
    'game_2048_rules': 'Use the arrow keys to move the tiles. When two tiles with the same number touch, they merge into one. Try to create the 2048 tile.',
    'game_2048_history': 'Created in 2014 by Italian web developer Gabriele Cirulli, it became a viral hit.',
    'game_2048_fact1': 'It is mathematically possible to reach a tile of 131,072.',

    // Uno
    'game_uno_name': 'Uno',
    'game_uno_desc': 'The classic card game of matching colors and numbers.',
    'game_uno_rules': 'Players take turns matching a card in their hand with the current card shown on top of the deck. Special cards change the gameplay. Be the first to get rid of all your cards.',
    'game_uno_history': 'Developed in 1971 by Merle Robbins, it is now a staple of family game nights worldwide.',
    'game_uno_fact1': 'The name "Uno" means "one" in both Spanish and Italian.',
    
    // Pricing
    'plan_free_name': 'Free Plan',
    'plan_preview_name': 'Preview',
    'plan_a_name': 'Apprentice',
    'plan_b_name': 'Journeyman',
    'plan_c_name': 'Master',
    'plan_corp_name': 'Corporate',
    'plan_free_feat1': 'Play up to 3 games',
    'plan_free_feat2': 'Community access',
    'plan_preview_feat1': 'Test new games',
    'plan_preview_feat2': 'Provide feedback',
    'plan_a_feat1': '3 games, 25 plays/month',
    'plan_a_feat2': 'Max 10 plays per game',
    'plan_b_feat1': '20 games, 100 plays/month',
    'plan_b_feat2': 'Max 50 plays per game',
    'plan_c_feat1': '50 games, 500 plays/month',
    'plan_c_feat2': 'Max 250 plays per game',
    'plan_corp_feat1': 'Custom game access',
    'plan_corp_feat2': 'Whitelabeling options',
};

const es: Record<string, string> = {
    // General
    'alile_play': 'Alile Play',
    'game_library': 'Biblioteca de Juegos',
    'pricing': 'Precios',
    'coming_soon': 'Próximamente',
    'play_now': 'Jugar Ahora',
    'back_to_library': 'Volver a la Biblioteca',
    'start_game': 'Empezar Juego',
    'game_lobby': 'Lobby del Juego',
    'rules': 'Reglas',
    'history': 'Historia',
    'fun_facts': 'Datos Curiosos',
    'game_options': 'Opciones del Juego',
    'select_level': 'Selecciona tu nivel',
    'skill_beginner': 'Principiante',
    'skill_intermediate': 'Intermedio',
    'skill_advanced': 'Avanzado',
    'skill_easy': 'Fácil',
    'skill_medium': 'Medio',
    'skill_hard': 'Difícil',
    'option_difficulty': 'Dificultad de la IA',
    'option_difficulty_level': 'Nivel de Dificultad',
    'ai_chat_placeholder': 'Pregúntale a Alile AI...',
    'ai_chat_title': 'Asistente Alile AI',
    'error_boundary_title': '¡Uy! Algo salió mal.',
    'error_boundary_message': 'Ocurrió un error inesperado. Por favor, actualiza la página para continuar.',
    'new_game': 'Nuevo Juego',
    'reset_board': 'Reiniciar Tablero',
    'featured_plan': 'Destacado',
    'btn_select_plan': 'Seleccionar Plan',

    // Categories
    'game_category_strategy': 'Estrategia',
    'game_category_puzzle': 'Puzzle',
    'game_category_word': 'Palabras',
    'game_category_arcade': 'Arcade',
    'game_category_board_card': 'Juegos de Mesa y Cartas',

    // Chess
    'game_chess_name': 'Ajedrez',
    'game_chess_desc': 'El juego definitivo de estrategia e intelecto. Haz jaque mate al rey oponente para ganar.',
    'game_chess_rules': 'Cada jugador comienza con 16 piezas. El objetivo es hacer jaque mate al rey del oponente. Cada tipo de pieza se mueve de una manera diferente.',
    'game_chess_history': 'Originario de la India en el siglo VI, el ajedrez se extendió a Persia y al mundo musulmán antes de llegar a Europa.',
    'game_chess_fact1': 'La partida de ajedrez teóricamente más larga posible es de 5.949 movimientos.',
    'game_chess_fact2': 'La palabra "Jaque Mate" proviene de la frase persa "Shah Mat", que significa "el Rey ha muerto".',
    'game_chess_fact3': 'El cerebro de un gran maestro es una maravilla del reconocimiento de patrones, capaz de recordar decenas de miles de posiciones de juego.',
    'chess_turn_your': 'Tu Turno',
    'chess_turn_ai': 'Turno de la IA',
    'chess_check': '¡Jaque!',
    'chess_checkmate': '¡Jaque Mate!',
    'chess_draw': '¡Tablas!',
    
    // Sudoku
    'game_sudoku_name': 'Sudoku',
    'game_sudoku_desc': 'Un rompecabezas de lógica basado en la colocación de números.',
    'game_sudoku_rules': 'Llena una cuadrícula de 9x9 de modo que cada columna, cada fila y cada una de las nueve subcuadrículas de 3x3 contengan todos los dígitos del 1 al 9.',
    'game_sudoku_history': 'La versión moderna del Sudoku fue inventada en los Estados Unidos en 1979, pero se popularizó en Japón en la década de 1980.',
    'game_sudoku_fact1': 'Hay 6,670,903,752,021,072,936,960 posibles cuadrículas de Sudoku.',
    'game_sudoku_fact2': 'El nombre Sudoku es una abreviatura japonesa de "Su-ji wa dokushin ni kagiru", que significa "los números deben ser únicos".',
    'sudoku_congrats': '¡Felicidades!',
    'sudoku_solved': '¡Resolviste el rompecabezas!',

    // Word Master
    'game_wordmaster_name': 'Maestro de Palabras',
    'game_wordmaster_desc': 'Adivina la palabra secreta de cinco letras en seis intentos.',
    'game_wordmaster_rules': 'Cada intento debe ser una palabra válida de cinco letras. Presiona enter para enviar. Después de cada intento, el color de las fichas cambiará para mostrar qué tan cerca estuvo tu intento de la palabra. Verde es una letra correcta en el lugar correcto. Amarillo es una letra correcta en el lugar incorrecto. Gris es una letra que no está en la palabra.',
    'game_wordmaster_history': 'Inspirado en el clásico juego de lápiz y papel Jotto y el programa de televisión Lingo, explotó en popularidad como "Wordle" a principios de la década de 2020.',
    'game_wordmaster_fact1': 'La letra inicial más común para las palabras de cinco letras en inglés es la \'S\'.',
    'game_wordmaster_fact2': 'Las vocales de uso común como A, E, I, O, U son cruciales para resolver el rompecabezas rápidamente.',
    'wordmaster_win': '¡Lo tienes!',
    'wordmaster_lose': '¡Buen intento! La palabra era:',
    'wordmaster_invalid_word': 'Palabra no válida',
};

const fr: Record<string, string> = {
    'alile_play': 'Alile Play',
    'game_library': 'Bibliothèque de Jeux',
    'pricing': 'Tarifs',
    'coming_soon': 'Bientôt Disponible',
    'play_now': 'Jouer Maintenant',
    'back_to_library': 'Retour à la Bibliothèque',
    'start_game': 'Commencer le Jeu',
    'game_lobby': 'Lobby du Jeu',
    'rules': 'Règles',
    'history': 'Histoire',
    'fun_facts': 'Faits Amusants',
    'game_options': 'Options du Jeu',
    'select_level': 'Choisissez votre niveau',
    'skill_beginner': 'Débutant',
    'skill_intermediate': 'Intermédiaire',
    'skill_advanced': 'Avancé',
    'skill_easy': 'Facile',
    'skill_medium': 'Moyen',
    'skill_hard': 'Difficile',
    'option_difficulty': 'Difficulté de l\'IA',
    'option_difficulty_level': 'Niveau de Difficulté',
    'ai_chat_placeholder': 'Demandez à Alile AI...',
    'ai_chat_title': 'Assistant Alile AI',
    'new_game': 'Nouveau Jeu',
    'reset_board': 'Réinitialiser',
    'featured_plan': 'En vedette',
    'btn_select_plan': 'Choisir ce Plan',
    'game_category_strategy': 'Stratégie',
    'game_category_puzzle': 'Puzzle',
    'game_category_word': 'Mots',
    'game_category_arcade': 'Arcade',
    'game_category_board_card': 'Jeu de Plateau et Cartes',
    'game_chess_name': 'Échecs',
    'game_chess_desc': 'Le jeu ultime de stratégie et d\'intellect. Mettez le roi adverse en échec et mat pour gagner.',
    'sudoku_congrats': 'Félicitations !',
    'sudoku_solved': 'Vous avez résolu le puzzle !',
    'wordmaster_win': 'Vous l\'avez !',
    'wordmaster_lose': 'Bien essayé ! Le mot était :',
    'wordmaster_invalid_word': 'Mot non valide',
};

const de: Record<string, string> = {
    'alile_play': 'Alile Play',
    'game_library': 'Spielebibliothek',
    'pricing': 'Preise',
    'coming_soon': 'Kommt Bald',
    'play_now': 'Jetzt Spielen',
    'back_to_library': 'Zurück zur Bibliothek',
    'start_game': 'Spiel Starten',
    'game_lobby': 'Spiele-Lobby',
    'rules': 'Regeln',
    'history': 'Geschichte',
    'fun_facts': 'Wissenswertes',
    'game_options': 'Spieloptionen',
    'select_level': 'Wähle dein Level',
    'skill_beginner': 'Anfänger',
    'skill_intermediate': 'Mittel',
    'skill_advanced': 'Fortgeschritten',
    'skill_easy': 'Leicht',
    'skill_medium': 'Mittel',
    'skill_hard': 'Schwer',
    'option_difficulty': 'KI-Schwierigkeit',
    'option_difficulty_level': 'Schwierigkeitsgrad',
    'ai_chat_placeholder': 'Fragen Sie Alile AI...',
    'ai_chat_title': 'Alile AI Assistent',
    'new_game': 'Neues Spiel',
    'reset_board': 'Zurücksetzen',
    'featured_plan': 'Empfohlen',
    'btn_select_plan': 'Plan Wählen',
    'game_category_strategy': 'Strategie',
    'game_category_puzzle': 'Puzzle',
    'game_category_word': 'Wort',
    'game_category_arcade': 'Arcade',
    'game_category_board_card': 'Brett & Karte',
    'game_chess_name': 'Schach',
    'game_chess_desc': 'Das ultimative Spiel der Strategie und des Intellekts. Setzen Sie den gegnerischen König schachmatt, um zu gewinnen.',
    'sudoku_congrats': 'Glückwunsch!',
    'sudoku_solved': 'Sie haben das Rätsel gelöst!',
    'wordmaster_win': 'Du hast es!',
    'wordmaster_lose': 'Guter Versuch! Das Wort war:',
    'wordmaster_invalid_word': 'Ungültiges Wort',
};

const zh: Record<string, string> = {
    'alile_play': 'Alile Play',
    'game_library': '游戏库',
    'pricing': '价格',
    'coming_soon': '即将推出',
    'play_now': '现在玩',
    'back_to_library': '返回游戏库',
    'start_game': '开始游戏',
    'game_lobby': '游戏大厅',
    'rules': '规则',
    'history': '历史',
    'fun_facts': '有趣的事实',
    'game_options': '游戏选项',
    'select_level': '选择你的等级',
    'skill_beginner': '初学者',
    'skill_intermediate': '中级',
    'skill_advanced': '高级',
    'skill_easy': '简单',
    'skill_medium': '中等',
    'skill_hard': '困难',
    'option_difficulty': 'AI 难度',
    'option_difficulty_level': '难度等级',
    'ai_chat_placeholder': '询问 Alile AI...',
    'ai_chat_title': 'Alile AI 助手',
    'new_game': '新游戏',
    'reset_board': '重置',
    'featured_plan': '精选',
    'btn_select_plan': '选择计划',
    'game_category_strategy': '策略',
    'game_category_puzzle': '益智',
    'game_category_word': '文字',
    'game_category_arcade': '街机',
    'game_category_board_card': '桌游和纸牌',
    'game_chess_name': '国际象棋',
    'game_chess_desc': '终极策略与智力游戏。将死对手的国王即可获胜。',
    'sudoku_congrats': '恭喜！',
    'sudoku_solved': '你解开了谜题！',
    'wordmaster_win': '你猜对了！',
    'wordmaster_lose': '再接再厉！答案是：',
    'wordmaster_invalid_word': '无效单词',
};

const pt: Record<string, string> = {
    'alile_play': 'Alile Play',
    'game_library': 'Biblioteca de Jogos',
    'pricing': 'Preços',
    'coming_soon': 'Em Breve',
    'play_now': 'Jogar Agora',
    'back_to_library': 'Voltar para a Biblioteca',
    'start_game': 'Começar Jogo',
    'game_lobby': 'Lobby do Jogo',
    'rules': 'Regras',
    'history': 'História',
    'fun_facts': 'Curiosidades',
    'game_options': 'Opções de Jogo',
    'select_level': 'Selecione seu nível',
    'skill_beginner': 'Iniciante',
    'skill_intermediate': 'Intermediário',
    'skill_advanced': 'Avançado',
    'skill_easy': 'Fácil',
    'skill_medium': 'Médio',
    'skill_hard': 'Difícil',
    'option_difficulty': 'Dificuldade da IA',
    'option_difficulty_level': 'Nível de Dificuldade',
    'ai_chat_placeholder': 'Pergunte à Alile AI...',
    'ai_chat_title': 'Assistente Alile AI',
    'new_game': 'Novo Jogo',
    'reset_board': 'Reiniciar',
    'featured_plan': 'Destaque',
    'btn_select_plan': 'Selecionar Plano',
    'game_category_strategy': 'Estratégia',
    'game_category_puzzle': 'Quebra-cabeça',
    'game_category_word': 'Palavras',
    'game_category_arcade': 'Arcade',
    'game_category_board_card': 'Jogo de Tabuleiro e Cartas',
    'game_chess_name': 'Xadrez',
    'game_chess_desc': 'O jogo definitivo de estratégia e intelecto. Dê xeque-mate no rei do oponente para vencer.',
    'sudoku_congrats': 'Parabéns!',
    'sudoku_solved': 'Você resolveu o quebra-cabeça!',
    'wordmaster_win': 'Você conseguiu!',
    'wordmaster_lose': 'Bela tentativa! A palavra era:',
    'wordmaster_invalid_word': 'Palavra inválida',
};

// To avoid excessive boilerplate, we'll merge the english translations as a fallback for other languages
const mergeWithEnglish = (translations: Record<string, string>) => ({ ...en, ...translations });

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: en,
  es: mergeWithEnglish(es),
  fr: mergeWithEnglish(fr),
  de: mergeWithEnglish(de),
  zh: mergeWithEnglish(zh),
  pt: mergeWithEnglish(pt),
};

export const DEFAULT_USER: User = {
  name: 'Guest Player',
  role: 'public',
  preferences: {
    theme: Theme.DARK,
    language: Language.EN,
    skillLevels: {
      'chess': SkillLevel.INTERMEDIATE,
      'sudoku': 'medium',
    },
  },
  subscription: {
    planId: 'free',
    gamesPlayedThisMonth: 0,
    gamePlays: {},
  },
};

export const PLANS: MonetizationPlan[] = [
    { id: 'free', nameKey: 'plan_free_name', price: 0, featuresKey: ['plan_free_feat1', 'plan_free_feat2'], isFeatured: false },
    { id: 'preview', nameKey: 'plan_preview_name', price: 5, featuresKey: ['plan_preview_feat1', 'plan_preview_feat2'], isFeatured: false },
    { id: 'a', nameKey: 'plan_a_name', price: 10, featuresKey: ['plan_a_feat1', 'plan_a_feat2'], isFeatured: true, monthlyGameLimit: 25, perGameLimit: 10 },
    { id: 'b', nameKey: 'plan_b_name', price: 30, featuresKey: ['plan_b_feat1', 'plan_b_feat2'], isFeatured: false, monthlyGameLimit: 100, perGameLimit: 50 },
    { id: 'c', nameKey: 'plan_c_name', price: 50, featuresKey: ['plan_c_feat1', 'plan_c_feat2'], isFeatured: false, monthlyGameLimit: 500, perGameLimit: 250 },
    // { id: 'corp', nameKey: 'plan_corp_name', price: -1, featuresKey: ['plan_corp_feat1', 'plan_corp_feat2'], isFeatured: false },
];
